// <auto-generated />
using System;
using HTquanlyhoinghi_UNETI2_TI17A3HN.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyHoiNghi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002094505_ThemNguoiThamDuDangKyCheckIn")]
    partial class ThemNguoiThamDuDangKyCheckIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.CheckIn", b =>
                {
                    b.Property<string>("MaCheckIn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDangKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCheckIn");

                    b.HasIndex("MaDangKy")
                        .IsUnique();

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DangKyThamDu", b =>
                {
                    b.Property<string>("MaDangKy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoTuChoiHuy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiThamDu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaThamDu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaNguoiThamDu");

                    b.HasIndex("MaSuKien");

                    b.ToTable("DangKyThamDus");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DiaDiem", b =>
                {
                    b.Property<string>("MaDiaDiem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChuaToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiaDiem");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.LoaiSuKien", b =>
                {
                    b.Property<string>("MaLoaiSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiSuKien");

                    b.HasIndex("TenLoaiSuKien")
                        .IsUnique();

                    b.ToTable("LoaiSuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.NguoiThamDu", b =>
                {
                    b.Property<string>("MaNguoiThamDu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DonViCongTac")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiThamDu");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NguoiThamDus");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.PhienSuKien", b =>
                {
                    b.Property<string>("MaPhienSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DienGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhienSuKien");

                    b.HasIndex("MaSuKien");

                    b.ToTable("PhienSuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.Property<string>("MaSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaLoaiSuKien");

                    b.ToTable("SuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.CheckIn", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DangKyThamDu", "DangKyThamDu")
                        .WithOne("CheckIn")
                        .HasForeignKey("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.CheckIn", "MaDangKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyThamDu");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DangKyThamDu", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.NguoiThamDu", "NguoiThamDu")
                        .WithMany("DangKyThamDus")
                        .HasForeignKey("MaNguoiThamDu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", "SuKien")
                        .WithMany()
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiThamDu");

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.NguoiThamDu", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.PhienSuKien", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", "SuKien")
                        .WithMany("PhienSuKiens")
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DiaDiem", "DiaDiem")
                        .WithMany()
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.LoaiSuKien", "LoaiSuKien")
                        .WithMany()
                        .HasForeignKey("MaLoaiSuKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("LoaiSuKien");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DangKyThamDu", b =>
                {
                    b.Navigation("CheckIn");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.NguoiThamDu", b =>
                {
                    b.Navigation("DangKyThamDus");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.Navigation("PhienSuKiens");
                });
#pragma warning restore 612, 618
        }
    }
}
