// <auto-generated />
using System;
using HTquanlyhoinghi_UNETI2_TI17A3HN.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyHoiNghi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929085853_ThemModule2_SuKien_Phiens")]
    partial class ThemModule2_SuKien_Phiens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DiaDiem", b =>
                {
                    b.Property<string>("MaDiaDiem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChuaToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiaDiem");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.LoaiSuKien", b =>
                {
                    b.Property<string>("MaLoaiSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLoaiSuKien");

                    b.HasIndex("TenLoaiSuKien")
                        .IsUnique();

                    b.ToTable("LoaiSuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.PhienSuKien", b =>
                {
                    b.Property<string>("MaPhienSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DienGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhienSuKien");

                    b.HasIndex("MaSuKien");

                    b.ToTable("PhienSuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.Property<string>("MaSuKien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiSuKien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSuKien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSuKien");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaLoaiSuKien");

                    b.ToTable("SuKiens");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.PhienSuKien", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", "SuKien")
                        .WithMany("PhienSuKiens")
                        .HasForeignKey("MaSuKien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuKien");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.DiaDiem", "DiaDiem")
                        .WithMany()
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.LoaiSuKien", "LoaiSuKien")
                        .WithMany()
                        .HasForeignKey("MaLoaiSuKien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("LoaiSuKien");
                });

            modelBuilder.Entity("HTquanlyhoinghi_UNETI2_TI17A3HN.Models.SuKien", b =>
                {
                    b.Navigation("PhienSuKiens");
                });
#pragma warning restore 612, 618
        }
    }
}
